In [1]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd
import numpy as np

#### Standard Scaling

In [2]:
a = np.array([[10, 200, 0.3],
              [9,230, 0.1],
              [9.5, 225, 0.45]])

pa = pd.DataFrame(a, columns=['X1','X2','X3'])
print("Mean: \n", pa.mean())
print('STD: \n ', pa.std())

Mean: 
 X1      9.500000
X2    218.333333
X3      0.283333
dtype: float64
STD: 
  X1     0.500000
X2    16.072751
X3     0.175594
dtype: float64


In [5]:
scaler = StandardScaler().set_output(transform='pandas')
scaler.fit(pa)
print(scaler.mean_)
print(scaler.scale_)

[  9.5        218.33333333   0.28333333]
[ 0.40824829 13.12334646  0.14337209]


#### MinMax Scaling

In [9]:
scaler = MinMaxScaler().set_output(transform='pandas')
scaler.fit(pa)
print(scaler.data_min_)
print(scaler.data_min_)

[9.e+00 2.e+02 1.e-01]
[9.e+00 2.e+02 1.e-01]


In [10]:
scaler.transform(pa)

X1        X2        X3
0  1.0  0.000000  0.571429
1  0.0  1.000000  0.000000
2  0.5  0.833333  1.000000